#!/bin/sh

if [ "$1" = "update" ]; then
    # Check if the script is run as root
    if [ "$EUID" -ne 0 ]; then
        echo -e "\033[1;91mERROR\033[0m: Please run as root"
        exit
    fi

    killall spotifytools

    echo -e "\033[1mCloning repository...\033[0m"
    cd /tmp/
    git clone https://github.com/XECortex/spotifytools.git
    cd spotifytools/
    echo -e "\n"

    ./install.sh

    echo -e "\033[1mCleaning up...\033[0m"
    rm -rf /tmp/spotifytools
    exit
fi

/opt/spotifytools/main.py "$@"
